In [3]:
import numpy as np

In [4]:
test = """
7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
"""

# Part One

In [54]:
def get_diffs(row):
    diffs = np.diff(row)
    return diffs

def check_if_all_same_sign(row):
    # chek if all are positive
    if np.all(row > 0):
        if np.all(row <= 3):
            return True
        return False
    if np.all(row < 0):
        if np.all(row >= -3):
            return True
        return False
    return False


def check_all_rows(arr):
    counter = 0
    for i in range(arr.shape[0]):
        counter += int(check_if_all_same_sign(arr[i,:]))
    return counter

def is_row_safe(row):
    diffs = get_diffs(row)
    return check_if_all_same_sign(diffs)

    
def get_total_number_of_safe(input_file):
    counter = 0
    with open(input_file, 'r') as file:
        for line in file:
            row = np.array(list(map(int, line.split())))
            counter += int(is_row_safe(row))
    return counter

    

In [51]:
get_total_number_of_safe('test.txt')

7 6 4 2 1

[7 6 4 2 1]
1 2 7 8 9

[1 2 7 8 9]
9 7 6 2 1

[9 7 6 2 1]
1 3 2 4 5

[1 3 2 4 5]
8 6 4 4 1

[8 6 4 4 1]
1 3 6 7 9
[1 3 6 7 9]


2

In [56]:
get_total_number_of_safe('input.txt')

252

# Part two

In [125]:
def is_row_safe_with_dampener(row):
    diffs = get_diffs(row)
    if check_if_all_same_sign(diffs):
        return True
    else:
        return dampener(row)

def dampener(row):
    diffs = get_diffs(row)

    answer = False
    # assume the row is increasing
    for i in range(len(row)-1):
        if (row[i+1] - row[i] <= 0 or row[i+1] - row[i] > 3):
            new_row = np.delete(row, i)
            #print(is_row_safe(new_row))
            answer = is_row_safe(new_row)
            if answer == False:
                new_row = np.delete(row, i+1)
                answer = is_row_safe(new_row)
    if answer:
        return answer

    # assume the row is decreasing
    for i in range(len(row)-1):
        if (row[i+1] - row[i] >= 0 or row[i+1] - row[i] < -3):
            new_row = np.delete(row, i)
            #print(is_row_safe(new_row))
            answer = is_row_safe(new_row)
            if answer == False:
                new_row = np.delete(row, i+1)
                answer = is_row_safe(new_row)
    return answer


def get_total_number_of_safe_with_dampener(input_file):
    counter = 0
    with open(input_file, 'r') as file:
        for line in file:
            row = np.array(list(map(int, line.split())))
            counter += int(is_row_safe_with_dampener(row))
    return counter

In [123]:
get_total_number_of_safe_with_dampener('test.txt')

4

In [124]:
get_total_number_of_safe_with_dampener('input.txt')

324